//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation.Transaction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mcda5510.dpenny.com", ConfigurationName="Transaction.TrxnWebService")]
    public interface TrxnWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeTransactionReturn")]
        bool removeTransaction(int trxnID);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeTransactionReturn")]
        System.Threading.Tasks.Task<bool> removeTransactionAsync(int trxnID);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HotelReservation.Transaction.updateTransactionResponse updateTransaction(HotelReservation.Transaction.updateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelReservation.Transaction.updateTransactionResponse> updateTransactionAsync(HotelReservation.Transaction.updateTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HotelReservation.Transaction.createTransactionResponse createTransaction(HotelReservation.Transaction.createTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelReservation.Transaction.createTransactionResponse> createTransactionAsync(HotelReservation.Transaction.createTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name getTransactionReturn from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HotelReservation.Transaction.getTransactionResponse getTransaction(HotelReservation.Transaction.getTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelReservation.Transaction.getTransactionResponse> getTransactionAsync(HotelReservation.Transaction.getTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTransaction", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.updateTransactionRequestBody Body;
        
        public updateTransactionRequest() {
        }
        
        public updateTransactionRequest(HotelReservation.Transaction.updateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class updateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double unitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double totalPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string expDate;
        
        public updateTransactionRequestBody() {
        }
        
        public updateTransactionRequestBody(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate) {
            this.trxnID = trxnID;
            this.Name = Name;
            this.CardNumber = CardNumber;
            this.unitPrice = unitPrice;
            this.qty = qty;
            this.totalPrice = totalPrice;
            this.expDate = expDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTransactionResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.updateTransactionResponseBody Body;
        
        public updateTransactionResponse() {
        }
        
        public updateTransactionResponse(HotelReservation.Transaction.updateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class updateTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateTransactionReturn;
        
        public updateTransactionResponseBody() {
        }
        
        public updateTransactionResponseBody(string updateTransactionReturn) {
            this.updateTransactionReturn = updateTransactionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createTransaction", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.createTransactionRequestBody Body;
        
        public createTransactionRequest() {
        }
        
        public createTransactionRequest(HotelReservation.Transaction.createTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class createTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double unitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double totalPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cardType;
        
        public createTransactionRequestBody() {
        }
        
        public createTransactionRequestBody(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string cardType) {
            this.trxnID = trxnID;
            this.Name = Name;
            this.CardNumber = CardNumber;
            this.unitPrice = unitPrice;
            this.qty = qty;
            this.totalPrice = totalPrice;
            this.expDate = expDate;
            this.cardType = cardType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createTransactionResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.createTransactionResponseBody Body;
        
        public createTransactionResponse() {
        }
        
        public createTransactionResponse(HotelReservation.Transaction.createTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class createTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createTransactionReturn;
        
        public createTransactionResponseBody() {
        }
        
        public createTransactionResponseBody(string createTransactionReturn) {
            this.createTransactionReturn = createTransactionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransaction", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.getTransactionRequestBody Body;
        
        public getTransactionRequest() {
        }
        
        public getTransactionRequest(HotelReservation.Transaction.getTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class getTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        public getTransactionRequestBody() {
        }
        
        public getTransactionRequestBody(int trxnID) {
            this.trxnID = trxnID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransactionResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public HotelReservation.Transaction.getTransactionResponseBody Body;
        
        public getTransactionResponse() {
        }
        
        public getTransactionResponse(HotelReservation.Transaction.getTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class getTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTransactionReturn;
        
        public getTransactionResponseBody() {
        }
        
        public getTransactionResponseBody(string getTransactionReturn) {
            this.getTransactionReturn = getTransactionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrxnWebServiceChannel : HotelReservation.Transaction.TrxnWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrxnWebServiceClient : System.ServiceModel.ClientBase<HotelReservation.Transaction.TrxnWebService>, HotelReservation.Transaction.TrxnWebService {
        
        public TrxnWebServiceClient() {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool removeTransaction(int trxnID) {
            return base.Channel.removeTransaction(trxnID);
        }
        
        public System.Threading.Tasks.Task<bool> removeTransactionAsync(int trxnID) {
            return base.Channel.removeTransactionAsync(trxnID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservation.Transaction.updateTransactionResponse HotelReservation.Transaction.TrxnWebService.updateTransaction(HotelReservation.Transaction.updateTransactionRequest request) {
            return base.Channel.updateTransaction(request);
        }
        
        public string updateTransaction(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate) {
            HotelReservation.Transaction.updateTransactionRequest inValue = new HotelReservation.Transaction.updateTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.updateTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.Name = Name;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            HotelReservation.Transaction.updateTransactionResponse retVal = ((HotelReservation.Transaction.TrxnWebService)(this)).updateTransaction(inValue);
            return retVal.Body.updateTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservation.Transaction.updateTransactionResponse> HotelReservation.Transaction.TrxnWebService.updateTransactionAsync(HotelReservation.Transaction.updateTransactionRequest request) {
            return base.Channel.updateTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservation.Transaction.updateTransactionResponse> updateTransactionAsync(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate) {
            HotelReservation.Transaction.updateTransactionRequest inValue = new HotelReservation.Transaction.updateTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.updateTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.Name = Name;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            return ((HotelReservation.Transaction.TrxnWebService)(this)).updateTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservation.Transaction.createTransactionResponse HotelReservation.Transaction.TrxnWebService.createTransaction(HotelReservation.Transaction.createTransactionRequest request) {
            return base.Channel.createTransaction(request);
        }
        
        public string createTransaction(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string cardType) {
            HotelReservation.Transaction.createTransactionRequest inValue = new HotelReservation.Transaction.createTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.createTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.Name = Name;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.cardType = cardType;
            HotelReservation.Transaction.createTransactionResponse retVal = ((HotelReservation.Transaction.TrxnWebService)(this)).createTransaction(inValue);
            return retVal.Body.createTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservation.Transaction.createTransactionResponse> HotelReservation.Transaction.TrxnWebService.createTransactionAsync(HotelReservation.Transaction.createTransactionRequest request) {
            return base.Channel.createTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservation.Transaction.createTransactionResponse> createTransactionAsync(int trxnID, string Name, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string cardType) {
            HotelReservation.Transaction.createTransactionRequest inValue = new HotelReservation.Transaction.createTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.createTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.Name = Name;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.cardType = cardType;
            return ((HotelReservation.Transaction.TrxnWebService)(this)).createTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservation.Transaction.getTransactionResponse HotelReservation.Transaction.TrxnWebService.getTransaction(HotelReservation.Transaction.getTransactionRequest request) {
            return base.Channel.getTransaction(request);
        }
        
        public string getTransaction(int trxnID) {
            HotelReservation.Transaction.getTransactionRequest inValue = new HotelReservation.Transaction.getTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.getTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            HotelReservation.Transaction.getTransactionResponse retVal = ((HotelReservation.Transaction.TrxnWebService)(this)).getTransaction(inValue);
            return retVal.Body.getTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservation.Transaction.getTransactionResponse> HotelReservation.Transaction.TrxnWebService.getTransactionAsync(HotelReservation.Transaction.getTransactionRequest request) {
            return base.Channel.getTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservation.Transaction.getTransactionResponse> getTransactionAsync(int trxnID) {
            HotelReservation.Transaction.getTransactionRequest inValue = new HotelReservation.Transaction.getTransactionRequest();
            inValue.Body = new HotelReservation.Transaction.getTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            return ((HotelReservation.Transaction.TrxnWebService)(this)).getTransactionAsync(inValue);
        }
    }
}
